import argparse


def get_args():
    parser = argparse.ArgumentParser(description='Parameter Configuration')
    # generative AI config
    parser.add_argument('--model_configs', type=str, default=None, help='model json-format configuration')
    parser.add_argument('--generative_model', type=str, default='gpt-4o', help='the generative model')

    # RAG config
    parser.add_argument('--embedding_model', type=str, default='retriever/bge-m3', help='the embedding model')
    parser.add_argument('--top_k', type=int, default=1, help='the number of returned information chunks')
    parser.add_argument('--dimension', type=int, default=1024, help='please refer to the embedding model')

    # generation source
    parser.add_argument('--from_corpus', type=str, default="False", help='whether to generate data from corpus')
    parser.add_argument('--from_choice_question', type=str, default="False", help='whether to generate data from test paper')
    parser.add_argument('--from_subjective_question', type=str, default='False', help='whether to generate data from subjective question')

    # generate from corpus
    parser.add_argument('--data_path', type=str, default='example/corpus_2.txt', help='input data path')
    parser.add_argument('--knowledge_source', type=str, default='example/KB/KB.txt', help='knowledge source for generate form corpus')
    parser.add_argument('--knowledge_index', type=str, default='example/KB/KB_index.index', help='knowledge index')
    parser.add_argument('--knowledge_embedding', type=str, default='example/KB/kb_embeddings.npy', help='knowledge embeddings')
    parser.add_argument('--k', type=int, default=1, help='the number of data generated by one api call')

    # generate from paper test
    parser.add_argument('--exam_data', type=str, default='example/textpaper/merged_output.jsonl', help='the examination data path')
    parser.add_argument('--subjective_question', type=str, default='example/Statement_1.jsonl', help='the subjective question data path')

    parser.add_argument('--data_result', type=str, default='result/finetune', help='the save path of generated data path')

    return parser.parse_args()
