* [1]**Introduction** (Overview of the operation/works)
* [2]**This method statement outlines the general method for the feasibility study on temporary widening along the SSK Drive (Works Area W8A, W8B) including but not limited to topography survey inspection, survey result recording and inspection records analysis. The content mainly describes the procedure of the abovementioned survey works, as well as instrumentation and equipment required for carrying out the survey works. Risk and safety precautions are also considered. The principle methods as described in the following sections are subject to review during construction and may be amended if required. The **Inspection and Test Plan (ITP)** is enclosed to ensure all parties involve are fully aware of the work procedure (See Appendix B).
* [3]**Scope of Works**
* [4]**The general working procedures outlined in this method statement are applicable to the following scopes of work:** \(\bullet\) **Topography Survey along SSK Drive for feasibility study on temporary widening (approx. 870m)** \(\bullet\) **Survey of site area occupied by CEDD Contract Contract No. NL/2020/07**
* [5]**Responsibilities for Activities described within Method Statement**
* [6]**CSHK is responsible to inspect and carry out the construction works. The responsible persons are listed below and be responsible for the activities:** [7]**Company & Name & Position & Contact No.** [8]**Howard Siu & Construction Manager & 9495 9399** **CF Chan & Construction Manager & 9668 7888** **Anthony He & Assistant Construction & 6822 1099** Manager & **Kanson Woo & Senior Engineer & 6289 0390** **CSHK** Andrew Lo & Graduate Engineer & 6764 6649** **Leung Kwok Fung & Safety Manager & 9683 3846** Ernest Young & Assistant Safety Officer & 6055 5319** **Lau Yu Tat & Surveyor & 9419 0614** **Cheung Siu Kei & Superintendent & 9080 3168** **Build King & Vincent Kwan & Deputy Site Agent & 9833 1313**
* [7]**Construction Manager Responsible for overall administration, monitoring, controlling progress and quality of works in a safe manner.** [8]**Engineer Responsible for developing works procedures, controlling progress and quality of works in a safe manner. They also have to implement safety at works area for workers via guidance from safety officers.** [8]**This document is controlled in soft copy.** [9]**Any hard copies seen are uncontrolled unless** **Chopper with a red control stamp**Page 3 of 12**

[MISSING_PAGE_FAIL:4]

### 6.2 Topography Survey

Topography Survey along SSK Drive for the Feasibility Study on Temporary Widening will be carried out along the SSK Drive (approx. 870m) with the planned extent shown in Appendix A. In which, the as-built road profile, existing ground level, location of existing features shall be recorded by survey team. The information will be used to determine the extent of temporary widening of SSK Drive.

Figure 6.2 - 1 Existing ELS Works by CEDD Contract Contract No. NL/2020/07 at SSK Drive

Figure 6.2 - 2 Site Container Area by CEDD Contract Contract No. NL/2020/07 at SSK Drive

[MISSING_PAGE_FAIL:7]

[MISSING_PAGE_FAIL:8]

## Appendix A Layout plan and typical section of works

[MISSING_PAGE_EMPTY:10]

## Appendix B Inspection and Test Plan (ITP)INSPECTION AND TEST PLAN

[1]

**Section A. Pre-activities submissions (e.g., MSITP submission, foreign submission inc. temp, works, drop drawings, materials submissions, etc.)**

**Section B. Materials on-site inspection and test sampling (e.g., rebux, capapiler, execute, etc.)**

**Section C. Construction works in sequence (e.g. setting out, rebux fixing, framework execution, etc.)**

## Appendix C Technical Data of Equipment- Oyster Bay Station and Associated Works Method Statement for Feasibility Study on Temporary Widening Rev: at SSK Drive

\begin{tabular}{|p{42.7pt}|p{42.7pt}|p{42.7pt}|p{42.7pt}|p{42.7pt}|p{42.7pt}|p{42.7pt}|p{42.7pt}|p{42.7pt}|p{42.7pt}|} \hline \multicolumn{1}{|c|}{Method Statement No.:} & \multicolumn{2}{c|}{Initial Risk} & \multicolumn{2}{c|}{Mitigated Risk} & \multicolumn{2}{c|}{Classification} & \multicolumn{2}{c|}{Classification} & \multicolumn{2}{c|}{Classification} & \multicolumn{2}{c|}{Classification} & \multicolumn{2}{c|}{\multirow{2}{*}{Responsible Person Person}} \\ \cline{4-4} \cline{6-9} \multicolumn{1}{|c|}{} & \multicolumn{1}{p{42.7pt}|}{Frequency} & \multicolumn{1}{p{42.7pt}|}{Consequence} & \multicolumn{1}{p{42.7pt}|}{Fake} & \multicolumn{1}{p{42.7pt}|}{Frequency} & \multicolumn{1}{p{42.7pt}|}{Fake} & \multicolumn{1}{p{42.7pt}|}{Frequency} & \multicolumn{1}{p{42.7pt}|}{Fake Class} & \multicolumn{1}{p{42.7pt}|}{Fake Class} \\ \hline

_Frequency_